package dev.rafaelbrauner.flowvoice.ui.theme

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

@Immutable
data class FlowVoiceColors(
    val isDark: Boolean,
    val background: Color,
    val surface: Color,
    val chrome: Color,
    val surfaceRaised: Color,
    val key: Color,
    val field: Color,
    val hairline: Color,
    val hairlineCard: Color,
    val hairlineInput: Color,
    val textPrimary: Color,
    val textSecondary: Color,
    val textSecondaryStrong: Color,
    val textMuted: Color,
    val textTertiary: Color,
    val textTimestamp: Color,
    val noteBody: Color,
    val keyValue: Color,
    val iconMuted: Color,
    val accent: Color,
    val accentPressed: Color,
    val accentText: Color,
    val accentSurface: Color,
    val accentBorder: Color,
    val accentBorderSoft: Color,
    val onAccent: Color,
    val provisional: Color,
    val destructive: Color,
    val destructiveText: Color,
    val heroTop: Color,
    val heroBottom: Color,
    val heroBorder: Color,
    val heroTitle: Color,
    val heroSubtitle: Color,
    val statusPillBackground: Color,
    val statusPillBorder: Color,
    val primaryButtonContainer: Color,
    val primaryButtonContainerPressed: Color,
    val primaryButtonContent: Color,
    val outlineButtonContainer: Color,
    val outlineButtonBorder: Color,
    val outlineButtonContent: Color,
    val toggleOnTrack: Color,
    val toggleOnKnob: Color,
    val toggleOffTrack: Color,
    val toggleOffKnob: Color,
    val chip: Color,
    val chipContent: Color,
    val badgeInactive: Color,
    val badgeInactiveContent: Color,
    val avatar: Color,
    val rowHighlight: Color,
)

val FlowVoiceOrange = Color(0xFFFF7A1A)
val FlowVoiceOrangeOnLight = Color(0xFFB34700)
private val FlowVoiceOrangePressed = Color(0xFFFF9A4D)
private val FlowVoiceInk = Color(0xFF0C0D10)
private val FlowVoiceCoral = Color(0xFFFF6B5E)
private val PaperInk = Color(0xFF101114)

fun darkFlowVoiceColors(): FlowVoiceColors = FlowVoiceColors(
    isDark = true,
    background = FlowVoiceInk,
    surface = Color(0xFF14171B),
    chrome = Color(0xFF0F1114),
    surfaceRaised = Color(0xFF1B1E23),
    key = Color(0xFF22262B),
    field = Color(0xFF0F1114),
    hairline = Color.White.copy(alpha = 0.07f),
    hairlineCard = Color.White.copy(alpha = 0.06f),
    hairlineInput = Color.White.copy(alpha = 0.09f),
    textPrimary = Color(0xFFF2F3F5),
    textSecondary = Color(0xFF9BA2A9),
    textSecondaryStrong = Color(0xFFB9BFC6),
    textMuted = Color(0xFF7C838B),
    textTertiary = Color(0xFF6E757D),
    textTimestamp = Color(0xFF5D646C),
    noteBody = Color(0xFFD5D8DC),
    keyValue = Color(0xFFE4E6E9),
    iconMuted = Color(0xFF8A9099),
    accent = FlowVoiceOrange,
    accentPressed = FlowVoiceOrangePressed,
    accentText = FlowVoiceOrange,
    accentSurface = FlowVoiceOrange.copy(alpha = 0.10f),
    accentBorder = FlowVoiceOrange.copy(alpha = 0.35f),
    accentBorderSoft = FlowVoiceOrange.copy(alpha = 0.30f),
    onAccent = FlowVoiceInk,
    provisional = Color(0xFF9AA1A9),
    destructive = FlowVoiceCoral,
    destructiveText = FlowVoiceCoral,
    heroTop = Color(0xFF171B1E),
    heroBottom = Color(0xFF121417),
    heroBorder = Color.White.copy(alpha = 0.07f),
    heroTitle = Color(0xFFF2F3F5),
    heroSubtitle = Color(0xFF7C838B),
    statusPillBackground = Color(0xFF15181C),
    statusPillBorder = FlowVoiceOrange.copy(alpha = 0.30f),
    primaryButtonContainer = FlowVoiceOrange,
    primaryButtonContainerPressed = FlowVoiceOrangePressed,
    primaryButtonContent = FlowVoiceInk,
    outlineButtonContainer = Color.Transparent,
    outlineButtonBorder = Color.White.copy(alpha = 0.14f),
    outlineButtonContent = Color(0xFFB9BFC6),
    toggleOnTrack = FlowVoiceOrange,
    toggleOnKnob = FlowVoiceInk,
    toggleOffTrack = Color(0xFF2A2F36),
    toggleOffKnob = Color(0xFF8A9099),
    chip = Color(0xFF191C20),
    chipContent = Color(0xFFC6CAD0),
    badgeInactive = Color(0xFF22262B),
    badgeInactiveContent = Color(0xFF8A9099),
    avatar = Color(0xFF2A2F36),
    rowHighlight = Color(0xFF181B1F),
)

fun lightFlowVoiceColors(): FlowVoiceColors = FlowVoiceColors(
    isDark = false,
    background = Color(0xFFF4F2ED),
    surface = Color(0xFFFFFDF9),
    chrome = Color(0xFFEFEDE7),
    surfaceRaised = Color(0xFFE7E4DC),
    key = Color(0xFFE7E4DC),
    field = Color(0xFFEFEDE7),
    hairline = Color.Black.copy(alpha = 0.09f),
    hairlineCard = Color.Black.copy(alpha = 0.09f),
    hairlineInput = Color.Black.copy(alpha = 0.10f),
    textPrimary = PaperInk,
    textSecondary = Color(0xFF6B7078),
    textSecondaryStrong = Color(0xFF6B7078),
    textMuted = Color(0xFF6B7078),
    textTertiary = Color(0xFF8B9098),
    textTimestamp = Color(0xFF8B9098),
    noteBody = PaperInk,
    keyValue = PaperInk,
    iconMuted = Color(0xFF8B9098),
    accent = FlowVoiceOrange,
    accentPressed = FlowVoiceOrangePressed,
    accentText = FlowVoiceOrangeOnLight,
    accentSurface = FlowVoiceOrangeOnLight.copy(alpha = 0.08f),
    accentBorder = FlowVoiceOrangeOnLight.copy(alpha = 0.35f),
    accentBorderSoft = FlowVoiceOrangeOnLight.copy(alpha = 0.30f),
    onAccent = FlowVoiceInk,
    provisional = Color(0xFF8B9098),
    destructive = FlowVoiceCoral,
    destructiveText = Color(0xFFC0392B),
    heroTop = PaperInk,
    heroBottom = PaperInk,
    heroBorder = Color.Transparent,
    heroTitle = Color(0xFFF4F2ED),
    heroSubtitle = Color(0xFF8B9098),
    statusPillBackground = PaperInk,
    statusPillBorder = Color.Transparent,
    primaryButtonContainer = PaperInk,
    primaryButtonContainerPressed = Color(0xFF26282D),
    primaryButtonContent = FlowVoiceOrange,
    outlineButtonContainer = Color(0xFFFFFDF9),
    outlineButtonBorder = Color.Black.copy(alpha = 0.10f),
    outlineButtonContent = PaperInk,
    toggleOnTrack = PaperInk,
    toggleOnKnob = FlowVoiceOrange,
    toggleOffTrack = Color(0xFFE7E4DC),
    toggleOffKnob = Color(0xFF8B9098),
    chip = Color(0xFFE7E4DC),
    chipContent = PaperInk,
    badgeInactive = Color(0xFFE7E4DC),
    badgeInactiveContent = Color(0xFF6B7078),
    avatar = Color(0xFFE7E4DC),
    rowHighlight = Color(0xFFEFEDE7),
)
